# Generated by Django 5.1.2 on 2024-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='price',
            field=models.FloatField(),
        ),
    ]
